# The folder where your applications are in. [Optional] it defaults to "src"
#businessRoot: "src"

# Is Hirudo in development mode? [Optional]
debug: true

defaultApplication: "KitchenSink"
# Indeed, you can put whatever configuration variables needed here: