# The folder where your applications are in. [Optional] it defaults to "src"
#businessRoot: "src"

# Is Hirudo in development mode? [Optional]
debug: true

# This is the default module, this is used if no module is requested the value is  
# in format: "AppName::ModuleName::methodName".[Optional]
defaultModule: "KitchenSink::Welcome::index"

# This is a module to be called in case of any exception, the value is in format: 
# "AppName::ModuleName::methodName"
onModuleNotFound: "KitchenSink::Errors::notFound"

# This is a module to be called if a requested module doesn't exist, the value is 
# in format: "AppName::ModuleName::methodName"
onError: "KitchenSink::Errors::index"

# Indeed, you can put whatever configuration variables needed here:

# Yes, this is a DBAL configuration for doctrine, supposing that you are using the
# Hirudo's DoctrineDataAccess extension ;)
dbal:
  dbname: mydatabase
  user: root
  password: 123456
  host: localhost
  driver: pdo_mysql