# The folder where your applications are in. [Optional]
businessRoot: "src"
# Is Hirudo in development mode? [Optional]
debug: true
# This is a module to be called in case of any exception, the value is in format: "AppName::ModuleName::methodName"
onModuleNotFound: "KitchenSink::Errors::notFound"
# This is a module to be called if a requested module doesn't exist, the value is in format: "AppName::ModuleName::methodName"
onError: "KitchenSink::Errors::index"

# A db connection [Optional]
sa-db-connection: { dsn: "mysql:host=localhost;dbname=myDataBase", user: "root", password: 123456}

# Indeed, you can put whatever configuration variables needed here:
