metadata_manager: Hirudo\Core\DependencyInjection\AnnotationsBasedDependenciesManager

implementation_package:
  #The request data.
  - Hirudo\Impl\Joomla\V15\JoomlaRequest
  #The URL builder.
  - Hirudo\Impl\Joomla\V15\JoomlaRouting
  #The session Manager.
  - Hirudo\Impl\Joomla\V15\JoomlaSession
  #The current user.
  - Hirudo\Impl\Joomla\V15\JoomlaPrincipal
  #The configuration manager.
  - Hirudo\Impl\StandAlone\SAppConfig
  #The templating system.
  - Hirudo\Impl\Common\Templating\SmartyTemplating
  #The Sql Model
  - Hirudo\Impl\Joomla\Models\Components\Sql\JoomlaQueryFactory
  #The Asset system
  - Hirudo\Impl\Joomla\V15\JoomlaAssets
  #The page context
  - Hirudo\Impl\Joomla\V15\JoomlaPage
