metadata_manager: Hirudo\Core\DependencyInjection\AnnotationsBasedDependenciesManager

implementation_package:
  #The request data.
  - Hirudo\Impl\StandAlone\SARequest
  #The URL builder.
  - Hirudo\Impl\StandAlone\SARouting
  #The session Manager.
  - Hirudo\Impl\StandAlone\SASession
  #The current user.
  - Hirudo\Impl\StandAlone\SAPrincipal
  #The configuration manager.
  - Hirudo\Impl\StandAlone\SAppConfig
  #The templating system.
  - Hirudo\Impl\Templating\Smarty\SmartyTemplating
  #The Asset system
  - Hirudo\Impl\StandAlone\SAssets
  #The page context
  - Hirudo\Impl\StandAlone\SAPage
