metadata_manager: Hirudo\Core\DependencyInjection\AnnotationsBasedDependenciesManager

implementation_package:
  #The request data.
  - Hirudo\Impl\Joomla\V30\JoomlaRequest
  #The URL builder.
  - Hirudo\Impl\Joomla\V30\JoomlaRouting
  #The session Manager.
  - Hirudo\Impl\Joomla\V30\JoomlaSession
  #The current user.
  - Hirudo\Impl\Joomla\V30\JoomlaPrincipal
  #The configuration manager.
  - Hirudo\Impl\StandAlone\SAppConfig
  #The templating system.
  - Hirudo\Impl\Templating\Smarty\SmartyTemplating
  #The Asset system
  - Hirudo\Impl\Joomla\V30\JoomlaAssets
  #The page context
  - Hirudo\Impl\Joomla\V30\JoomlaPage
