metadata_manager: Hirudo\Core\DependencyInjection\AnnotationsBasedDependenciesManager

cache: { type: filesystem, cache_folder: "ext::cache" }

implementation_package:
  #The request data.
  - Hirudo\Impl\StandAlone\SARequest
  #The URL builder.
  - Hirudo\Impl\StandAlone\SARouting
  #The session Manager.
  - Hirudo\Impl\StandAlone\SASession
  #The current user.
  - Hirudo\Impl\StandAlone\SAPrincipal
  #The configuration manager.
  - Hirudo\Impl\StandAlone\SAppConfig
  #The templating system.
  - Hirudo\Impl\Common\Templating\SmartyTemplating
  #The Sql Model
  - Hirudo\Impl\StandAlone\Models\Components\Sql\SAQueryFactory
  #The Asset system
  - Hirudo\Impl\StandAlone\SAssets
