metadata_manager: Hirudo\Core\DependencyInjection\AnnotationsBasedDependenciesManager

cache: { type: filesystem, cache_folder: "ext::cache" }

implementation_package:
  #The request data.
  - Hirudo\Impl\Drupal\DrupalRequest
  #The URL builder.
  - Hirudo\Impl\Drupal\DrupalRouting
  #The session Manager.
  - Hirudo\Impl\Drupal\DrupalSession
  #The current user.
  - Hirudo\Impl\Drupal\DrupalPrincipal
  #The configuration manager.
  - Hirudo\Impl\StandAlone\SAppConfig
  #The templating system.
  - Hirudo\Impl\Common\Templating\SmartyTemplating
  #The Asset system
  - Hirudo\Impl\Drupal\DrupalAssets
