<?php

require_once 'init.php';

/**
 * «Copyright 2012 Jeysson José Guevara Mendivil(JeyDotC)» 
 * 
 * This file is part of Hirudo.
 * 
 * Hirudo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 *  Hirudo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with Hirudo.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * This hook gives support for drupal 6
 * 
 * @param string $op The block operation
 * @param mixed $delta A unique id for the block
 * @param array $edit
 * 
 * @return array|void
 */
function hirudo6_block($op = 'list', $delta = 0, $edit = array()) {
    if ($op == "list") {
        return hirudo_block_info();
    } else if ($op == "view") {
        return hirudo_block_view($delta);
    }
}

/**
 * This method provides the Hirudo block information that allows Hirudo
 * applications to be rendered on drupal.
 * 
 * @return array The block configuration.
 */
function hirudo_block_info() {
    return array(
        "hirudo" => array(
            "info" => "Hirudo framework",
            'cache' => BLOCK_NO_CACHE,
            "visibility" => 1,
            "pages" => "App",
            "region" => "content"
        )
    );
}

/**
 * Renders the Hirudo block. Also invokes the Hirudo process.
 * 
 * @param string $delta The block's delta, it should be "hirudo" in order to render. 
 * @return array The rendered block
 */
function hirudo_block_view($delta = '') {
    $block = array();

    if ($delta == "hirudo") {
        //Yep, a Dirty Quick fix to hide node's title for this block
        //drupal_add_js("(function ($) { $('.title').hide() })(jQuery);", array('type' => 'inline', 'scope' => 'footer'));

        $manager = new \Hirudo\Core\ModulesManager(array(
                    //The request data.
                    'Hirudo\Impl\Drupal\DrupalRequest',
                    //The URL builder.
                    'Hirudo\Impl\Drupal\DrupalRouting',
                    //The session Manager.
                    'Hirudo\Impl\Drupal\DrupalSession',
                    //The current user.
                    'Hirudo\Impl\Drupal\DrupalPrincipal',
                    //The configuration manager.
                    'Hirudo\Impl\StandAlone\SAppConfig',
                    //The templating system.
                    'Hirudo\Impl\Common\Templating\SmartyTemplating',
                    //The Asset system
                    'Hirudo\Impl\Drupal\DrupalAssets',
                ));

        $block = array(
            "subject" => "<none>",
            "content" => $manager->run()
        );
    }

    return $block;
}

function hirudo6_node_info() {
    return array(
        "hirudo" => array(
            "name" => "Hirudo PHP Web Framework",
            "module" => "hirudo", // For drupal 6
            "description" => "A node to hold the Hirudo app presentations.",
            "has_title" => false,
            "has_body" => false
        )
    );
}

/**
 * For drupal 6.
 * 
 * @param type $op
 * @param type $info
 */
function hirudo6_node_type($op, $info) {
    if ($op == "insert" && $info->type == "hirudo") {
        db_query("SELECT nid FROM {node} WHERE type = 'hirudo'");
        if (db_affected_rows() == 0) {
            $fakeNode = new stdClass();

            $fakeNode->uid = 1;
            $fakeNode->status = 1;
            $fakeNode->type = "hirudo";
            $fakeNode->name = "JeyDotC";
            $fakeNode->is_new = true;

            node_save($fakeNode);
            
            variable_set("fakenode_nid", $fakeNode->nid);
            
            $source = "node/{$fakeNode->nid}";
            $alias = "App";
            path_set_alias($source, $alias);
        }
    }
}

?>