<?php

/**
 * «Copyright 2012 Jeysson José Guevara Mendivil(JeyDotC)» 
 * 
 * This file is part of Hirudo.
 * 
 * Hirudo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 *  Hirudo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with Hirudo.  If not, see <http://www.gnu.org/licenses/>.
 */
if (!defined("HIRUDO_DRUPAL_MODULE")) {
    define("HIRUDO_DRUPAL_MODULE", "hirudo6");
}

function hirudo6_menu() {
    $menu = array();
    $menu["App"] = array(
        "page callback" => "hirudo6_run",
        "access callback" => true,
    );
    return $menu;
}

function hirudo6_run() {
    $result = run_manager();
    if (Hirudo\Core\Context\ModulesContext::instance()->getRequest()->isAjax()) {
        echo $result;
    } else {
        return $result;
    }
}

function run_manager() {
    require_once 'init.php';
    $manager = new \Hirudo\Core\ModulesManager("drupal");
    return $manager->run();
}

?>