<?php

/**
 * «Copyright 2012 Jeysson José Guevara Mendivil(JeyDotC)» 
 * 
 * This file is part of Hirudo.
 * 
 * Hirudo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 *  Hirudo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with Hirudo.  If not, see <http://www.gnu.org/licenses/>.
 */
require_once 'init.php';

use Hirudo\Core\ModulesManager;

/**
 * This method provides the Hirudo block information that allows Hirudo
 * applications to be rendered on drupal.
 * 
 * @return array The block configuration.
 */
function hirudo_block_info() {
    return array(
        "hirudo" => array(
            "info" => "Hirudo framework",
            'cache' => DRUPAL_NO_CACHE,
            "visibility" => BLOCK_VISIBILITY_LISTED,
            "pages" => "App",
        )
    );
}

/**
 * Renders the Hirudo block. Also invokes the Hirudo process.
 * 
 * @param string $delta The block's delta, it should be "hirudo" in order to render. 
 * @return array The rendered block
 */
function hirudo_block_view($delta = '') {
    $block = array();

    if ($delta == "hirudo") {
        //Yep, a Dirty Quick fix to hide node's title for this block
        drupal_add_js("(function ($) { $('.title').hide() })(jQuery);", array('type' => 'inline', 'scope' => 'footer'));

        $manager = new ModulesManager(array(
                    //The request data.
                    'Hirudo\Impl\Drupal\DrupalRequest',
                    //The URL builder.
                    'Hirudo\Impl\Drupal\DrupalRouting',
                    //The session Manager.
                    'Hirudo\Impl\Drupal\DrupalSession',
                    //The current user.
                    'Hirudo\Impl\Drupal\DrupalPrincipal',
                    //The configuration manager.
                    'Hirudo\Impl\StandAlone\SAppConfig',
                    //The templating system.
                    'Hirudo\Impl\Common\Templating\SmartyTemplating',
                    //The Asset system
                    'Hirudo\Impl\Drupal\DrupalAssets',
                ));

        $block = array(
            "subject" => "<none>",
            "content" => $manager->run()
        );
    }

    return $block;
}

?>