<?php

/**
 * «Copyright 2012 Jeysson José Guevara Mendivil(JeyDotC)» 
 * 
 * This file is part of Hirudo.
 * 
 * Hirudo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 *  Hirudo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with Hirudo.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * This method provides the Hirudo block information that allows Hirudo
 * applications to be rendered on drupal.
 * 
 * @return array The block configuration.
 */
function hirudo8_block_info() {
    return array(
        "hirudo" => array(
            "info" => "Hirudo framework",
            'cache' => DRUPAL_NO_CACHE,
            "visibility" => BLOCK_VISIBILITY_LISTED,
            "pages" => "App",
        )
    );
}

/**
 * Renders the Hirudo block. Also invokes the Hirudo process.
 * 
 * @param string $delta The block's delta, it should be "hirudo" in order to render. 
 * @return array The rendered block
 */
function hirudo8_block_view($delta = '') {
    $block = array();

    if ($delta == "hirudo") {
        require_once 'init.php';

        $nid = variable_get("fakenode_nid", 0);
        //Yep, a Dirty Quick fix to hide node's title for this block
        drupal_add_js("(function ($) { $('#node-$nid').hide() })(jQuery);", 'inline', 'footer');

        $manager = new \Hirudo\Core\ModulesManager(array(
                    //The request data.
                    'Hirudo\Impl\Drupal\DrupalRequest',
                    //The URL builder.
                    'Hirudo\Impl\Drupal\DrupalRouting',
                    //The session Manager.
                    'Hirudo\Impl\Drupal\DrupalSession',
                    //The current user.
                    'Hirudo\Impl\Drupal\DrupalPrincipal',
                    //The configuration manager.
                    'Hirudo\Impl\StandAlone\SAppConfig',
                    //The templating system.
                    'Hirudo\Impl\Common\Templating\SmartyTemplating',
                    //The Asset system
                    'Hirudo\Impl\Drupal\DrupalAssets',
                ));

        $block = array(
            "subject" => "<none>",
            "content" => $manager->run()
        );
    }

    return $block;
}

function hirudo8_node_info() {
    return array(
        "hirudo" => array(
            "name" => "Hirudo PHP Web Framework",
            "base" => "hirudo",
            "description" => "A node to hold the Hirudo app presentations.",
            "has_title" => false,
        )
    );
}

function hirudo8_node_type_insert($info) {
    if ($info->type == "hirudo") {
        $result = db_query("SELECT nid FROM {node} WHERE type = 'hirudo'");
        if ($result->rowCount() == 0) {
            $fakeNode = entity_create("node", array(
                "uid" => 1,
                "status" => 1,
                "type" => "hirudo",
                "language" => "und",
                "name" => "JeyDotC",
                "is_new" => true,
                'langcode' => LANGUAGE_NOT_SPECIFIED,
                    ));
            
            $fakeNode->save();

            variable_set("fakenode_nid", $fakeNode->nid);

            $source = "node/{$fakeNode->nid}";
            $alias = "App";
            $path = array(
                "source" => $source,
                "alias" => $alias
            );
            path_save($path);
        }
    }
}

?>