# This is the default module, this is used if no module is requested the value is  
# in format: "AppName::ModuleName::methodName".[Optional]
defaultModule: "KitchenSink::Welcome::index"

# This is a module to be called if a requested module doesn't exist, the value is 
# in format: "AppName::ModuleName::methodName"
onModuleNotFound: "KitchenSink::Errors::notFound"

# Indeed, you can put whatever configuration variables needed here: